# This worflow is primarily for platform/devops tools that need to be deployed into K8s cluster
# or tools that don't belong to Terraform
name: 'Workflow - Deploy Platform Tools'

on:
  push:
    branches:
      - feature/**
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"
  ENVIRONMENT_STAGE: "dev"
  ROLE_TO_ASSUME : "arn:aws:iam::539247466139:role/platform-tools-24b-redhat-GHA-role"

jobs:
  deploy-platform-tools:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: GitHubActionsRoleSession
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Backend - Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: versus/backend
          IMAGE_TAG: ${{ github.sha }}
        working-directory: ./backend
        run: |
          echo "Registry: $REGISTRY"
          echo "Repository: $REPOSITORY"
          echo "Image Tag: $IMAGE_TAG"
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Login to AWS EKS
        run: "aws eks update-kubeconfig --name redhat-eks-cluster-dev"

      - name: Backend1 - Deploy App to Kubernetes
        run: |
          IMAGE_TAG=${{ github.sha }}
          helm upgrade --install versus-app-backend ./app-helm-chart/ \
            --values ./app-helm-chart/values/backend/dev-values.yaml \
            --set image.tag=$IMAGE_TAG \
            --namespace versus-app --create-namespace

      - name: Frontend - Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: versus/frontend
          IMAGE_TAG: ${{ github.sha }}
        working-directory: ./frontend
        run: |
          echo "Registry: $REGISTRY"
          echo "Repository: $REPOSITORY"
          echo "Image Tag: $IMAGE_TAG"
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # - name: Frontend - Deploy App to Kubernetes
      #   run: |
      #     IMAGE_TAG=${{ github.sha }}
      #     helm upgrade --install versus-app-frontend ./app-helm-chart/ \
      #       --values ./app-helm-chart/values/frontend/dev-values.yaml \
      #       --set image.tag=$IMAGE_TAG \
      #       --namespace versus-app --create-namespace